### ISSUE TITLE
Cannot load pollnet - multiple computers, pollnet.dll exists. 

### ISSUE THREAD

**Issue by seanhess** [soler91/noita-together#64]
Hey there, I really want to use your amazing mod, but I can't figure out how to make it work. I just tried on a brand new computer and I always get the same error. Below is the output of logger, it's saying it can't find pollnet like you mentioned, but pollnet.dll definitely exists in that folder. See this image: https://imgur.com/a/oxDq0we

What am I doing wrong? Anything I can do to get more information?

```
Noita (Apr 23 2021) - 20220320-174210
-------------------------------------------
Lua (DoFile) error at 'mods/noita-together/init.lua': [string "mods/noita-together/files/lib/pollnet.lua"]:62: cannot load module 'mods\noita-together\bin\pollnet': The specified module could not be found.

Lua error: [string "mods/noita-together/init.lua"]:203: attempt to call global 'SendWsEvent' (a nil value)
```

**Comment by soler91** [comment]
the fix for that is in the FAQ in the discord https://discord.gg/ex3XFkXCgM

but also here you go

When starting a new game, it says there was an error initializing the mod? Game crashing ? Lobby not ready ?
Download [this](https://cdn.discordapp.com/attachments/813255004965044224/881622064002396250/vcruntime140.dll) and move it to your noita folder (where noita.exe is)

**Comment by seanhess** [comment]
That fixed it thank you!
